disabled_rules:
- trailing_whitespace
- identifier_name
included:
excluded:
- Pods
- OpenMarket/SupportingFiles/AppDelegate.swift
- OpenMarket/SupportingFiles/SceneDelegate.swift
- OpenMarketTests/Network/Dummy/
